'use client'

import Image from 'next/image'
import { useRouter } from 'next/navigation'
import { useState } from 'react'

import { createClient } from '@/lib/supabase/client'

type Enrollment = {
  factorId: string
  qrCode: string
  secret: string
}

export function EnrollMfaForm() {
  const router = useRouter()
  const [enrollment, setEnrollment] = useState<Enrollment | null>(null)
  const [code, setCode] = useState('')
  const [error, setError] = useState('')
  const [isStarting, setIsStarting] = useState(false)
  const [isVerifying, setIsVerifying] = useState(false)

  async function startEnrollment() {
    setError('')
    setIsStarting(true)

    const supabase = createClient()
    const { data, error: enrollmentError } = await supabase.auth.mfa.enroll({
      factorType: 'totp',
      friendlyName: 'OPG Admin Authenticator',
    })

    setIsStarting(false)

    if (enrollmentError) {
      setError('Authenticator setup could not start. Sign out and try again.')
      return
    }

    setEnrollment({
      factorId: data.id,
      qrCode: data.totp.qr_code,
      secret: data.totp.secret,
    })
  }

  async function verifyEnrollment(event: React.FormEvent<HTMLFormElement>) {
    event.preventDefault()
    setError('')

    if (!enrollment || !/^\d{6}$/.test(code)) {
      setError('Enter the 6-digit code from your authenticator app.')
      return
    }

    setIsVerifying(true)
    const supabase = createClient()
    const { error: verifyError } =
      await supabase.auth.mfa.challengeAndVerify({
        factorId: enrollment.factorId,
        code,
      })
    setIsVerifying(false)

    if (verifyError) {
      setError('That code was not accepted. Wait for a new code and try again.')
      return
    }

    router.replace('/admin')
    router.refresh()
  }

  if (!enrollment) {
    return (
      <div className="auth-form">
        {error ? (
          <p className="form-message form-message--error" role="alert">
            {error}
          </p>
        ) : null}
        <button
          className="button"
          disabled={isStarting}
          onClick={startEnrollment}
          type="button"
        >
          {isStarting ? 'Starting setup…' : 'Set up authenticator app'}
        </button>
      </div>
    )
  }

  return (
    <form className="auth-form" onSubmit={verifyEnrollment}>
      <ol className="auth-steps">
        <li>Open your authenticator app.</li>
        <li>Scan this QR code or enter the setup key manually.</li>
        <li>Enter the 6-digit code generated by the app.</li>
      </ol>
      <div className="mfa-qr">
        <Image
          alt="QR code for the OPG administrator authenticator"
          height={220}
          src={enrollment.qrCode}
          unoptimized
          width={220}
        />
      </div>
      <div className="mfa-secret">
        <span>Manual setup key</span>
        <code>{enrollment.secret}</code>
      </div>
      <label className="field" htmlFor="enrollment-code">
        <span>6-digit verification code</span>
        <input
          autoComplete="one-time-code"
          id="enrollment-code"
          inputMode="numeric"
          maxLength={6}
          name="code"
          onChange={(event) =>
            setCode(event.target.value.replace(/\D/g, '').slice(0, 6))
          }
          pattern="[0-9]{6}"
          required
          type="text"
          value={code}
        />
      </label>
      {error ? (
        <p className="form-message form-message--error" role="alert">
          {error}
        </p>
      ) : null}
      <button className="button" disabled={isVerifying} type="submit">
        {isVerifying ? 'Verifying…' : 'Verify and continue'}
      </button>
    </form>
  )
}
